// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:75eb733c-c050-40ee-8078-2d92fcdbb398",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_GH5ZfYZwP",
    "aws_user_pools_web_client_id": "3pdrelplu7bt2e0ua72ia2mc1"
};


export default awsmobile;
